name: Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: "*"
  workflow_dispatch:
    inputs:
      name:
        description: "Manually running workflow..."
        required: true
        default: "To check"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd jslib && npm ci
      - run: cd jslib && npm run build --if-present
      - run: cd jslib && npm test

  publish:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd jslib && npm ci
      - run: cd jslib && npm run build
      - run: cd jslib && npm run semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
